import type { Permission } from "@/types";
import { SUPER_ADMIN_ROLE } from "@/types";

export const SYSTEM_PERMISSIONS: Omit<Permission, "active">[] = [
  { id: "view_dashboard", name: "View Dashboard", module: "dashboard" },
  { id: "view_inventory", name: "View Inventory", module: "inventory" },
  { id: "manage_inventory", name: "Manage Inventory", module: "inventory" },
  { id: "adjust_stock", name: "Adjust Stock", module: "inventory" },
  { id: "view_inventory_reports", name: "View Inventory Reports", module: "inventory" },
  { id: "view_sales", name: "View Sales", module: "sales" },
  { id: "create_sales", name: "Create Sales", module: "sales" },
  { id: "print_receipts", name: "Print Receipts", module: "sales" },
  { id: "view_customers", name: "View Customers", module: "customers" },
  { id: "manage_customers", name: "Manage Customers", module: "customers" },
  { id: "view_suppliers", name: "View Suppliers", module: "suppliers" },
  { id: "manage_suppliers", name: "Manage Suppliers", module: "suppliers" },
  { id: "view_purchases", name: "View Purchases", module: "purchases" },
  { id: "manage_purchases", name: "Manage Purchases", module: "purchases" },
  { id: "approve_purchases", name: "Approve Purchases", module: "purchases" },
  { id: "view_quotations", name: "View Quotations", module: "quotations" },
  { id: "manage_quotations", name: "Manage Quotations", module: "quotations" },
  { id: "view_proforma", name: "View Proforma Invoices", module: "proforma" },
  { id: "manage_proforma", name: "Manage Proforma Invoices", module: "proforma" },
  { id: "view_invoices", name: "View Invoices", module: "invoices" },
  { id: "manage_invoices", name: "Manage Invoices", module: "invoices" },
  { id: "view_receipts", name: "View Receipts", module: "receipts" },
  { id: "manage_receipts", name: "Manage Receipts", module: "receipts" },
  { id: "view_custom_orders", name: "View Custom Orders", module: "customOrders" },
  { id: "manage_custom_orders", name: "Manage Custom Orders", module: "customOrders" },
  { id: "view_accounting", name: "View Accounting", module: "accounting" },
  { id: "manage_accounting", name: "Manage Accounting", module: "accounting" },
  { id: "view_home_stitch_account", name: "View Home Stitch Account", module: "accounting" },
  { id: "manage_home_stitch_account", name: "Manage Home Stitch Account", module: "accounting" },
  { id: "view_financial_reports", name: "View Financial Reports", module: "accounting" },
  { id: "post_journal_entries", name: "Post Journal Entries", module: "accounting" },
  { id: "approve_expenses", name: "Approve Expenses", module: "accounting" },
  { id: "view_reports", name: "View Reports", module: "reports" },
  { id: "export_reports", name: "Export Reports", module: "reports" },
  { id: "view_settings", name: "View Settings", module: "settings" },
  { id: "manage_settings", name: "Manage Settings", module: "settings" },
  { id: "manage_users", name: "Manage Users", module: "administration" },
  { id: "manage_roles", name: "Manage Roles", module: "administration" },
  { id: "manage_permissions", name: "Manage Permissions", module: "administration" },
  { id: "view_audit_logs", name: "View Audit Logs", module: "administration" },
  { id: "view_expenses", name: "View Expenses", module: "expenses" },
  { id: "manage_expenses", name: "Manage Expenses", module: "expenses" },
  { id: "view_analytics", name: "View Analytics", module: "analytics" },
  { id: "view_notifications", name: "View Notifications", module: "notifications" },
];

export const ALL_PERMISSION_IDS = SYSTEM_PERMISSIONS.map((p) => p.id);

export interface SeedRole {
  id: string;
  name: string;
  description: string;
  permissions: string[];
  isSystem?: boolean;
}

export const SYSTEM_ROLES: SeedRole[] = [
  {
    id: SUPER_ADMIN_ROLE,
    name: "Super Admin",
    description: "Unrestricted access to all modules and system administration",
    permissions: ALL_PERMISSION_IDS,
    isSystem: true,
  },
  {
    id: "admin",
    name: "Administrator",
    description: "Full business access and user management",
    permissions: ALL_PERMISSION_IDS.filter(
      (p) => !["manage_permissions", "view_audit_logs"].includes(p)
    ),
    isSystem: true,
  },
  {
    id: "manager",
    name: "Manager",
    description: "Oversees business operations",
    permissions: [
      "view_dashboard",
      "view_inventory",
      "manage_inventory",
      "view_sales",
      "create_sales",
      "view_customers",
      "manage_customers",
      "view_suppliers",
      "view_purchases",
      "view_quotations",
      "manage_quotations",
      "view_proforma",
      "view_invoices",
      "view_receipts",
      "view_custom_orders",
      "view_reports",
      "export_reports",
      "view_home_stitch_account",
    ],
    isSystem: true,
  },
  {
    id: "cashier",
    name: "Cashier",
    description: "Handles sales transactions and receipts",
    permissions: [
      "view_dashboard",
      "view_sales",
      "create_sales",
      "print_receipts",
      "view_customers",
      "manage_customers",
      "view_receipts",
      "view_inventory",
      "view_home_stitch_account",
    ],
    isSystem: true,
  },
  {
    id: "storeKeeper",
    name: "Store Keeper",
    description: "Manages inventory and stock",
    permissions: [
      "view_dashboard",
      "view_inventory",
      "manage_inventory",
      "adjust_stock",
      "view_inventory_reports",
      "view_suppliers",
      "view_purchases",
      "manage_purchases",
      "view_home_stitch_account",
    ],
    isSystem: true,
  },
  {
    id: "stockManager",
    name: "Stock Manager",
    description: "Full control over stock levels, movements, and inventory operations",
    permissions: [
      "view_dashboard",
      "view_inventory",
      "manage_inventory",
      "adjust_stock",
      "view_inventory_reports",
      "view_suppliers",
      "manage_suppliers",
      "view_purchases",
      "manage_purchases",
      "approve_purchases",
      "view_reports",
      "export_reports",
      "view_notifications",
      "view_home_stitch_account",
    ],
    isSystem: true,
  },
  {
    id: "accountant",
    name: "Accountant",
    description: "Manages accounting and financial records",
    permissions: [
      "view_dashboard",
      "view_accounting",
      "manage_accounting",
      "view_home_stitch_account",
      "manage_home_stitch_account",
      "view_financial_reports",
      "post_journal_entries",
      "approve_expenses",
      "view_reports",
      "export_reports",
      "view_invoices",
      "view_receipts",
      "view_purchases",
      "view_suppliers",
      "view_customers",
      "view_expenses",
      "manage_expenses",
    ],
    isSystem: true,
  },
  {
    id: "tailor",
    name: "Tailor",
    description: "Handles custom tailoring orders",
    permissions: [
      "view_dashboard",
      "view_custom_orders",
      "manage_custom_orders",
      "view_customers",
      "view_inventory",
    ],
    isSystem: true,
  },
  {
    id: "viewer",
    name: "Viewer",
    description: "Read-only access to most modules",
    permissions: [
      "view_dashboard",
      "view_inventory",
      "view_sales",
      "view_customers",
      "view_suppliers",
      "view_purchases",
      "view_quotations",
      "view_proforma",
      "view_invoices",
      "view_receipts",
      "view_custom_orders",
      "view_reports",
    ],
    isSystem: true,
  },
];

/** Route prefix → required permission to access */
export const ROUTE_PERMISSIONS: Record<string, string> = {
  "/dashboard": "view_dashboard",
  "/inventory": "view_inventory",
  "/sales": "view_sales",
  "/customers": "view_customers",
  "/suppliers": "view_suppliers",
  "/purchases": "view_purchases",
  "/quotations": "view_quotations",
  "/proforma-invoices": "view_proforma",
  "/proforma": "view_proforma",
  "/invoices": "view_invoices",
  "/receipts": "view_receipts",
  "/custom-orders": "view_custom_orders",
  "/accounting/home-stitch": "view_home_stitch_account",
  "/accounting": "view_accounting",
  "/expenses": "view_expenses",
  "/reports": "view_reports",
  "/analytics": "view_analytics",
  "/notifications": "view_notifications",
  "/settings/users": "manage_users",
  "/settings/roles": "manage_roles",
  "/settings/permissions": "manage_permissions",
  "/settings/audit-logs": "view_audit_logs",
  "/settings/audit": "view_audit_logs",
  "/settings": "view_settings",
};
