import type { HubConfig } from "@/lib/erp/entity-config";

export const HUB_CONFIGS: Record<string, HubConfig> = {
  inventory: {
    id: "inventory",
    title: "Inventory Management",
    description: "Products, stock movements, valuation, and reorder alerts",
    permission: "view_inventory",
    links: [
      { title: "Products", description: "Manage product catalog", href: "/inventory/products", permission: "view_inventory" },
      { title: "Categories", description: "Product categories", href: "/inventory/categories", permission: "view_inventory" },
      { title: "Brands", description: "Optional brands per category", href: "/inventory/brands", permission: "view_inventory" },
      { title: "Stock In", description: "Receive stock", href: "/inventory/stock-in", permission: "adjust_stock" },
      { title: "Stock Out", description: "Issue stock", href: "/inventory/stock-out", permission: "adjust_stock" },
      { title: "Adjustments", description: "Stock adjustments", href: "/inventory/adjustments", permission: "adjust_stock" },
      { title: "Transfers", description: "Transfer between locations", href: "/inventory/transfers", permission: "adjust_stock" },
      { title: "Damaged Stock", description: "Record damaged items", href: "/inventory/damaged-stock", permission: "adjust_stock" },
      { title: "Returns", description: "Customer/supplier returns", href: "/inventory/returns", permission: "adjust_stock" },
      { title: "Movements", description: "Movement history", href: "/inventory/movements", permission: "view_inventory" },
      { title: "Valuation", description: "Inventory valuation", href: "/inventory/valuation", permission: "view_inventory" },
      { title: "Reorder Alerts", description: "Low stock alerts", href: "/inventory/reorder-alerts", permission: "view_inventory" },
    ],
  },
  sales: {
    id: "sales",
    title: "Sales & POS",
    description: "Point of sale, sales history, returns, and payments",
    permission: "view_sales",
    links: [
      { title: "POS Terminal", description: "Quick checkout", href: "/sales/pos", permission: "create_sales" },
      { title: "New Sale", description: "Create a sale", href: "/sales/new", permission: "create_sales" },
      { title: "Sales History", description: "All sales records", href: "/sales/history", permission: "view_sales" },
      { title: "Returns", description: "Process returns", href: "/sales/returns", permission: "create_sales" },
      { title: "Discounts", description: "Discount rules", href: "/sales/discounts", permission: "view_sales" },
      { title: "Payments", description: "Payment records", href: "/sales/payments", permission: "view_sales" },
    ],
  },
  customers: {
    id: "customers",
    title: "Customers",
    description: "Customer profiles, statements, and transaction history",
    permission: "view_customers",
    links: [
      { title: "All Customers", description: "Customer directory", href: "/customers", permission: "view_customers" },
      { title: "New Customer", description: "Add customer", href: "/customers/new", permission: "manage_customers" },
    ],
  },
  quotations: {
    id: "quotations",
    title: "Quotations",
    description: "Create and manage customer quotations",
    permission: "view_quotations",
    links: [
      { title: "All Quotations", description: "Quotation list", href: "/quotations", permission: "view_quotations" },
      { title: "New Quotation", description: "Create quotation", href: "/quotations/new", permission: "manage_quotations" },
    ],
  },
  proforma: {
    id: "proforma",
    title: "Proforma Invoices",
    description: "Proforma invoices and conversions",
    permission: "view_proforma",
    links: [
      { title: "All Proforma", description: "Proforma list", href: "/proforma-invoices", permission: "view_proforma" },
      { title: "New Proforma", description: "Create proforma", href: "/proforma-invoices/new", permission: "manage_proforma" },
    ],
  },
  purchases: {
    id: "purchases",
    title: "Purchases",
    description: "Purchase orders, receiving, and supplier purchases",
    permission: "view_purchases",
    links: [
      { title: "All Purchases", description: "Purchase records", href: "/purchases", permission: "view_purchases" },
      { title: "New Purchase", description: "Create purchase", href: "/purchases/new", permission: "manage_purchases" },
      { title: "Purchase Orders", description: "PO management", href: "/purchases/orders", permission: "view_purchases" },
      { title: "Receiving", description: "Goods receiving", href: "/purchases/receiving", permission: "manage_purchases" },
    ],
  },
  suppliers: {
    id: "suppliers",
    title: "Suppliers",
    description: "Supplier profiles, payments, and purchase history",
    permission: "view_suppliers",
    links: [
      { title: "All Suppliers", description: "Supplier directory", href: "/suppliers", permission: "view_suppliers" },
      { title: "New Supplier", description: "Add supplier", href: "/suppliers/new", permission: "manage_suppliers" },
    ],
  },
  customOrders: {
    id: "customOrders",
    title: "Custom Orders",
    description: "Tailored orders, production board, and delivery",
    permission: "view_custom_orders",
    links: [
      { title: "All Orders", description: "Custom order list", href: "/custom-orders", permission: "view_custom_orders" },
      { title: "New Order", description: "Create custom order", href: "/custom-orders/new", permission: "manage_custom_orders" },
      { title: "Production Board", description: "Kanban production view", href: "/custom-orders/production-board", permission: "view_custom_orders" },
    ],
  },
  accounting: {
    id: "accounting",
    title: "Accounting",
    description: "General ledger, financial statements, and cash management",
    permission: "view_accounting",
    links: [
      { title: "Home Stitch Account", description: "Main operating account ledger", href: "/accounting/home-stitch", permission: "view_home_stitch_account" },
      { title: "Chart of Accounts", description: "Account structure", href: "/accounting/chart-of-accounts", permission: "view_accounting" },
      { title: "Journal Entries", description: "Post entries", href: "/accounting/journal-entries", permission: "view_accounting" },
      { title: "General Ledger", description: "Ledger view", href: "/accounting/general-ledger", permission: "view_accounting" },
      { title: "Trial Balance", description: "Trial balance report", href: "/accounting/trial-balance", permission: "view_accounting" },
      { title: "Profit & Loss", description: "P&L statement", href: "/accounting/profit-loss", permission: "view_financial_reports" },
      { title: "Balance Sheet", description: "Balance sheet", href: "/accounting/balance-sheet", permission: "view_financial_reports" },
      { title: "Cash Flow", description: "Cash flow statement", href: "/accounting/cash-flow", permission: "view_financial_reports" },
      { title: "Cashbook", description: "Daily cash records", href: "/accounting/cashbook", permission: "view_accounting" },
      { title: "Receivables", description: "Accounts receivable", href: "/accounting/receivables", permission: "view_accounting" },
      { title: "Payables", description: "Accounts payable", href: "/accounting/payables", permission: "view_accounting" },
      { title: "Reconciliation", description: "Bank reconciliation", href: "/accounting/reconciliation", permission: "manage_accounting" },
      { title: "Bank Accounts", description: "Bank account setup", href: "/accounting/bank-accounts", permission: "manage_accounting" },
      { title: "Mobile Money", description: "Mobile money accounts", href: "/accounting/mobile-money-accounts", permission: "manage_accounting" },
      { title: "Owner Drawings", description: "Owner withdrawals", href: "/accounting/owner-drawings", permission: "manage_accounting" },
    ],
  },
  expenses: {
    id: "expenses",
    title: "Expenses",
    description: "Track business expenses and categories",
    permission: "view_expenses",
    links: [
      { title: "All Expenses", description: "Expense records", href: "/expenses", permission: "view_expenses" },
      { title: "New Expense", description: "Record expense", href: "/expenses/new", permission: "manage_expenses" },
      { title: "Categories", description: "Expense categories", href: "/expenses/categories", permission: "view_expenses" },
      { title: "Reports", description: "Expense reports", href: "/expenses/reports", permission: "view_expenses" },
    ],
  },
  reports: {
    id: "reports",
    title: "Reports",
    description: "Business reports and exports",
    permission: "view_reports",
    links: [
      { title: "Sales Reports", description: "Sales analytics", href: "/reports/sales", permission: "view_reports" },
      { title: "Inventory Reports", description: "Stock reports", href: "/reports/inventory", permission: "view_reports" },
      { title: "Customer Reports", description: "Customer analytics", href: "/reports/customers", permission: "view_reports" },
      { title: "Supplier Reports", description: "Supplier analytics", href: "/reports/suppliers", permission: "view_reports" },
      { title: "Purchase Reports", description: "Purchase analytics", href: "/reports/purchases", permission: "view_reports" },
      { title: "Custom Orders", description: "Order reports", href: "/reports/custom-orders", permission: "view_reports" },
      { title: "Financial Reports", description: "Financial summary", href: "/reports/financial", permission: "view_financial_reports" },
      { title: "Profitability", description: "Profit analysis", href: "/reports/profitability", permission: "view_reports" },
      { title: "Stock Movement", description: "Movement history", href: "/reports/stock-movement", permission: "view_reports" },
      { title: "Dead Stock", description: "Slow-moving inventory", href: "/reports/dead-stock", permission: "view_reports" },
      { title: "Top Products", description: "Best sellers", href: "/reports/top-products", permission: "view_reports" },
      { title: "Top Customers", description: "Top customers", href: "/reports/top-customers", permission: "view_reports" },
      { title: "Export Center", description: "Bulk export", href: "/reports/export", permission: "export_reports" },
    ],
  },
  analytics: {
    id: "analytics",
    title: "Analytics & BI",
    description: "Advanced analytics and insights",
    permission: "view_analytics",
    links: [
      { title: "Overview", description: "Analytics dashboard", href: "/analytics", permission: "view_analytics" },
      { title: "Sales Analytics", description: "Sales trends", href: "/analytics/sales", permission: "view_analytics" },
      { title: "Inventory Analytics", description: "Stock insights", href: "/analytics/inventory", permission: "view_analytics" },
      { title: "Customer Analytics", description: "Customer insights", href: "/analytics/customers", permission: "view_analytics" },
      { title: "Financial Analytics", description: "Financial trends", href: "/analytics/financial", permission: "view_analytics" },
      { title: "Profitability", description: "Margin analysis", href: "/analytics/profitability", permission: "view_analytics" },
      { title: "Trends", description: "Business trends", href: "/analytics/trends", permission: "view_analytics" },
      { title: "AI Insights", description: "Smart recommendations", href: "/analytics/ai-insights", permission: "view_analytics" },
    ],
  },
  notifications: {
    id: "notifications",
    title: "Notifications",
    description: "Alerts and system notifications",
    permission: "view_notifications",
    links: [
      { title: "All Notifications", description: "Notification inbox", href: "/notifications", permission: "view_notifications" },
      { title: "Alerts", description: "Critical alerts", href: "/notifications/alerts", permission: "view_notifications" },
      { title: "System", description: "System messages", href: "/notifications/system", permission: "view_notifications" },
    ],
  },
  settings: {
    id: "settings",
    title: "System Settings",
    description: "Company profile, security, and integrations",
    permission: "view_settings",
    links: [
      { title: "Company Profile", description: "Business details", href: "/settings/company", permission: "manage_settings" },
      { title: "Branding", description: "Logo and colors", href: "/settings/branding", permission: "manage_settings" },
      { title: "Document Templates", description: "PDF templates", href: "/settings/document-templates", permission: "manage_settings" },
      { title: "Email Settings", description: "Email configuration", href: "/settings/email", permission: "manage_settings" },
      { title: "Notifications", description: "Notification preferences", href: "/settings/notifications", permission: "manage_settings" },
      { title: "Security", description: "Security settings", href: "/settings/security", permission: "manage_settings" },
      { title: "Backup", description: "Data backup", href: "/settings/backup", permission: "manage_settings" },
      { title: "Integrations", description: "Third-party integrations", href: "/settings/integrations", permission: "manage_settings" },
      { title: "User Management", description: "Manage users", href: "/settings/users", permission: "manage_users" },
      { title: "Roles & Permissions", description: "RBAC management", href: "/settings/roles", permission: "manage_roles" },
      { title: "Permissions Catalog", description: "All permissions", href: "/settings/permissions", permission: "manage_permissions" },
      { title: "Audit Logs", description: "Activity logs", href: "/settings/audit-logs", permission: "view_audit_logs" },
    ],
  },
};
